import React, { useState , useEffect} from 'react'
import { Box, Button, Typography } from '@mui/material';
import Head from 'next/head';
import Aos from 'aos';
import 'aos/dist/aos.css';
import ManagerSwitcher from '../../components/ManagerSwitcher';
import ProjectCard from '../../components/card/ProjectCard';

const projects=[
  {
    image:'/images/yebox1.jpeg', 
    projectTitle:'Yebox', 
    projectSum:'A software company that provides software solutions and products ',
    btnClick:'https://www.yebox.io/', 
    lang:'vue',
  },
  {
    image:'/images/planvest.jpeg',
    projectTitle:'Planvest',  
    projectSum:'A fintech app that enables you invest, save, and apply for loans', 
    btnClick:'https://www.staging-co.planvest.africa/', 
    lang:'next',
  },
  {
    image:'/images/healthxp.jpeg',
    projectTitle:'HealthXP',  
    projectSum:'A healthTech startup that links patients with different doctors with data transfer  and security as priority', 
    btnClick:'https://healthxp-web.vercel.app/', 
    lang:'typescript',
  },
  {
    image:'/images/juris.jpeg',
    projectTitle:'Jurislex',  
    projectSum:'a lawfirm that provides legal solutions', 
    btnClick:'https://jurislexlawfirm.com/', 
    lang:'wordpress',
  },
  {
    image:'/images/calc.jpeg',
    projectTitle:'CalcIT',  
    projectSum:'a simple calculator', 
    btnClick:'https://mariamopeyemi.github.io/simple-calculator/', 
    lang:'javascript',
  },
  {
    image:'/images/flip.jpeg',
    projectTitle:'MemoFlip',  
    projectSum:'a flip memory retention game', 
    btnClick:'https://card-flip-memory-game.netlify.app/', 
    lang:'javascript',
  },          
  {
    image:'/images/yebora.jpeg',
    projectTitle:'Yebora',  
    projectSum:'Yebora; the collector. It is a crowdfunding platform to raise money for events', 
    btnClick:'https://www.yebora.com/', 
    lang:'react',
  },
  {
    image:'/images/yeborra.jpeg',
    projectTitle:'Shout',  
    projectSum:'an event management platform for celebration', 
    btnClick:'http://link-app-woad.vercel.app/', 
    lang:'react',
  },
  {
    image:'/images/mimi-store.png',
    projectTitle:'Mariam Store',  
    projectSum:'an ecommerce website for shopping variety of products', 
    btnClick:'https://ecommerce-nine-lac.vercel.app/', 
    lang:'next',
  },
]
const MYPROJECTS = [
  {title:"All", id:"ALL_PROJECT"},
  {title:"Vue js", id:"VUE_PROJECT"},
  {title:"React js", id:"REACT_PROJECT"},
  {title:"Next js", id:"NEXT_PROJECT"},
  {title:"Vanilla js", id:"JS_PROJECT"},
  {title:"Typescript", id:"TYPE_PROJECT"},
  {title:"Wordpress", id:"WORDPRESS_PROJECT"},
  
]
const Projects = () => {
  const [filterProject, setFilterProject] =useState([]);
  const [filterWordPress, setFilterWordPress] =useState([]);
  const [filterReact, setFilterReact] =useState([]);
  const [filterNext, setFilterNext] =useState([]);
  const [filterVue, setFilterVue] =useState([]);
  const [filterJavascript, setFilterJavascript] =useState([]);
  const [filterTypescript, setFilterTypescript] =useState([]);
  const [activeTable, setActiveTable] = useState("ALL_PROJECT");


  useEffect(() => {
    
  
  
  //  all projects
    setFilterProject(projects);
  // wordpress projects
    const wordpress = projects.filter(obj => {
      return obj.lang === 'wordpress';
    }); console.log(wordpress);

  // wordpress projects
    const reactP = projects.filter(obj => {
      return obj.lang === 'react';
    });console.log(reactP);
    
  // next projects
    const nextP = projects.filter(obj => {
      return obj.lang === 'next';
    });console.log(nextP);

  // vue projects
    const vueP = projects.filter(obj => {
      return obj.lang === 'vue';
    });console.log(vueP);

  // javascript projects
    const javascriptP = projects.filter(obj => {
      return obj.lang === 'javascript';
    });console.log(javascriptP);

  // typescript projects
    const typescriptP = projects.filter(obj => {
      return obj.lang === 'typescript';
    });console.log(typescriptP);
    
    setFilterWordPress(wordpress);
    setFilterReact(reactP);
    setFilterNext(nextP);
    setFilterVue(vueP);
    setFilterJavascript(javascriptP);
    setFilterTypescript(typescriptP);

  }, [])
  return (

    <Box sx={{
      backGroundColor: 'background.paper',
      display:'flex',
      flexDirection:'column',
      gap:'4rem',
      minHeight:'100vh',
      marginY:'3rem',
    }}>
      <Head>
        <title>Projects Opeyemi - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Typography
          sx={{marginX:'auto'}}>
            MY PROJECTS
            {/* MY PROJECTSrgb(248,208,148)brown rgb(45,42,36)coffee */}
          </Typography>
      <div>
        {/* MY PROJECTS Includes */}
       <Box sx={{ display: 'flex', marginBottom:'2rem', justifyContent:'space-around', marginX:'auto', flexDirection:'column'}}>
        <ManagerSwitcher
              handleChange={(item) => {
              setActiveTable(item);
              }}
              items={MYPROJECTS}
          ></ManagerSwitcher>
       </Box>
        <Box sx={{display: 'flex', gap: 4, width: '100%',  flexWrap: 'wrap', justifyContent:'space-between'}}>
          {activeTable === "ALL_PROJECT"  && <>
        {filterProject?.map((item, index) => {
            return (
            <ProjectCard 	data-aos='flip-left'
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}

           {activeTable === "VUE_PROJECT"  && <>
        {filterVue?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "WORDPRESS_PROJECT"  && <>
        {filterWordPress?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "REACT_PROJECT"  && <>
        {filterReact?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "NEXT_PROJECT"  && <>
        {filterNext?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "JS_PROJECT"  && <>
        {filterJavascript?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "TYPE_PROJECT"  && <>
        {filterTypescript?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
        </Box>
      </div>
    </Box>
  )
}

export default Projects;