import React, { useState , useEffect} from 'react'
import { Box, Button, Typography } from '@mui/material';
import Head from 'next/head';
import ManagerSwitcher from '../../components/ManagerSwitcher';
import ProjectCard from '../../components/card/ProjectCard';

const projects=[
  {
    image:'/images/yebox.jpeg', 
    projectTitle:'Yebox', 
    projectSum:'A software company that builds sme ',
    btnClick:'https://www.yebox.io/', 
    lang:'vue',
  },
  {
    image:'/images/planvest.jpeg',
    projectTitle:'Planvest',  
    projectSum:'A fintech app that enables you invest, save, and apply for loans', 
    btnClick:'https://www.staging-co.planvest.africa/', 
    lang:'next',
  },
  {
    image:'/images/healthxp.jpeg',
    projectTitle:'HealthXP',  
    projectSum:'A healthTech startup that links patients with diff doctors', 
    btnClick:'https://healthxp-web.vercel.app/', 
    lang:'typescript',
  },
  {
    image:'/images/juris.jpeg',
    projectTitle:'Jurislex',  
    projectSum:'a lawfirm ', 
    btnClick:'https://jurislexlawfirm.com/', 
    lang:'wordpress',
  },
  {
    image:'/images/calc.jpeg',
    projectTitle:'CalcIT',  
    projectSum:'a simple calculator', 
    btnClick:'https://mariamopeyemi.github.io/simple-calculator/', 
    lang:'javascript',
  },
  {
    image:'/images/flip.jpeg',
    projectTitle:'MemoFlip',  
    projectSum:'a flip memory retention game', 
    btnClick:'https://card-flip-memory-game.netlify.app/', 
    lang:'javascript',
  },          
  {
    image:'/images/yebora.jpeg',
    projectTitle:'Yebora',  
    btnClick:'https://opeyemi-portfolio.vercel.app/', 
    lang:'react',
  },
  {
    image:'/images/yeborra.jpeg',
    projectTitle:'Shout',  
    btnClick:'https://opeyemi-portfolio.vercel.app/', 
    lang:'react',
  },
]
const INVESTMENTS = [
  {title:"All", id:"ALL_PROJECT"},
  {title:"VUE", id:"VUE_PROJECT"},
  {title:"JAVASCRIPT", id:"JS_PROJECT"},
  {title:"TYPESCRIPT", id:"TYPE_PROJECT"},
  {title:"REACT", id:"REACT_PROJECT"},
  {title:"NEXT", id:"NEXT_PROJECT"},
  {title:"WORDPRESS", id:"WORDPRESS_PROJECT"},
  
]
const Projects = () => {
  const [filterProject, setFilterProject] =useState([]);
  const [filterWordPress, setFilterWordPress] =useState([]);
  const [filterReact, setFilterReact] =useState([]);
  const [filterNext, setFilterNext] =useState([]);
  const [filterVue, setFilterVue] =useState([]);
  const [filterJavascript, setFilterJavascript] =useState([]);
  const [filterTypescript, setFilterTypescript] =useState([]);
  const [activeTable, setActiveTable] = useState("ALL_PROJECT");

  useEffect(() => {
    
  
  
  //  all investment
    setFilterProject(projects);
  // wordpress investments
    const wordpress = projects.filter(obj => {
      return obj.lang === 'wordpress';
    }); console.log(wordpress);

  // wordpress investments
    const reactP = projects.filter(obj => {
      return obj.lang === 'react';
    });console.log(reactP);
    
  // next investments
    const nextP = projects.filter(obj => {
      return obj.lang === 'next';
    });console.log(nextP);

  // next investments
    const vueP = projects.filter(obj => {
      return obj.lang === 'vue';
    });console.log(vueP);

  // javascript investments
    const javascriptP = projects.filter(obj => {
      return obj.lang === 'javascript';
    });console.log(javascriptP);

  // typescript investments
    const typescriptP = projects.filter(obj => {
      return obj.lang === 'typescript';
    });console.log(typescriptP);
    
    setFilterWordPress(wordpress);
    setFilterReact(reactP);
    setFilterNext(nextP);
    setFilterVue(vueP);
    setFilterJavascript(javascriptP);
    setFilterTypescript(typescriptP);

  }, [])
  return (

    <Box sx={{
      backGroundColor: 'background.paper',
      display:'flex',
      flexDirection:'column',
      // alignItems: 'center',
      gap:'4rem',
      minHeight:'100vh',
      marginY:'3rem',
    }}>
      <Head>
        <title>Projects Opeyemi - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Typography
          sx={{marginX:'auto'}}>
            MY PROJECTSrgb(248,208,148)brown rgb(45,42,36)coffee
          </Typography>
      <div>
        {/* MY PROJECTS Includes */}
       <Box sx={{ display: 'flex', marginBottom:'2rem', justifyContent:'space-around', marginX:'auto', flexDirection:'column'}}>
        <ManagerSwitcher
              handleChange={(item) => {
              setActiveTable(item);
              }}
              // sx={{display:'flex',  backGroundColor:'blue'}}
              items={INVESTMENTS}
          ></ManagerSwitcher>
          {/* <Button onClick={filterWordPress} > All</Button>
          <Button onClick={filterReact} > Vue</Button> */}
          {/* <Button onClick={} > JavaScript</Button>
          <Button onClick={} > TypeScript</Button>
          <Button onClick={} > React</Button>
          <Button onClick={} > Next</Button>
          <Button onClick={} > Wordpress</Button> */}
       </Box>
           

            {/* <Typography> Vue: Yebox website</Typography>
            <Typography> Typescript: HealthXP website</Typography>
            <Typography> React: Yebora Website</Typography>
            <Typography> React: Yebora web App</Typography>
            <Typography> React: Shout web App</Typography>
            <Typography> Next: Planvest Web app</Typography>
            <Typography> Next: Portfolio Website</Typography>
            <Typography> Wordpress: Jurislex website</Typography> */}

        <Box sx={{display: 'flex', gap: 4, width: '100%',  flexWrap: 'wrap', justifyContent:'space-between'}}>
        {activeTable === "ALL_PROJECT"  && <>
        {filterProject?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}

           {activeTable === "VUE_PROJECT"  && <>
        {filterVue?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "WORDPRESS_PROJECT"  && <>
        {filterWordPress?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "REACT_PROJECT"  && <>
        {filterReact?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "NEXT_PROJECT"  && <>
        {filterNext?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "JS_PROJECT"  && <>
        {filterJavascript?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
           {activeTable === "TYPE_PROJECT"  && <>
        {filterTypescript?.map((item, index) => {
            return (
            <ProjectCard 
              key={index}
              image={item.image}
              projectTitle={item.projectTitle}
              projectSum={item.projectSum}
              btnClick={item.btnClick}
              />
          );})}
           </>}
{/* <div>
          <ProjectCard 
            image='/images/planvest.jpeg'
            projectTitle='Planvest'  
            projectSum='A fintech app that enables you invest, save, and apply for loans' 
            btnClick='https://www.staging-co.planvest.africa/' />
          <ProjectCard 
            image='/images/healthxp.jpeg'
            projectTitle='HealthXP'  
            projectSum='A healthTech startup that links patients with diff doctors' 
            btnClick='https://healthxp-web.vercel.app/' />
          <ProjectCard 
            image='/images/juris.jpeg'
            projectTitle='Jurislex'  
            projectSum='a lawfirm ' 
            btnClick='https://jurislexlawfirm.com/' />
          <ProjectCard 
            image='/images/calc.jpeg'
            projectTitle='CalcIT'  
            projectSum='a simple calculator' 
            btnClick='https://mariamopeyemi.github.io/simple-calculator/' />
          <ProjectCard 
            image='/images/flip.jpeg'
            projectTitle='MemoFlip'  
            projectSum='a flip memory retention game' 
            btnClick='https://card-flip-memory-game.netlify.app/' />          
          <ProjectCard 
            image='/images/yebora.jpeg'
            projectTitle='Yebora'  
            btnClick='https://opeyemi-portfolio.vercel.app/' />
          <ProjectCard 
            image='/images/yeborra.jpeg'
            projectTitle='Shout'  
            btnClick='https://opeyemi-portfolio.vercel.app/' />
</div> */}
        </Box>
      </div>
    </Box>
  )
}

export default Projects;


// projects=[
//           {
//             image:'/images/yebox.jpeg', 
//             projectTitle:'Yebox', 
//             projectSum:'A software company that builds sme ',
//             btnClick:'https://www.yebox.io/', 
//           },
//           {
//             image:'/images/planvest.jpeg',
//             projectTitle:'Planvest',  
//             projectSum:'A fintech app that enables you invest, save, and apply for loans', 
//             btnClick:'https://www.staging-co.planvest.africa/', 
//           },
//           {
//             image:'/images/healthxp.jpeg',
//             projectTitle:'HealthXP',  
//             projectSum:'A healthTech startup that links patients with diff doctors', 
//             btnClick:'https://healthxp-web.vercel.app/', 
//           },
//           {
//             image:'/images/juris.jpeg',
//             projectTitle:'Jurislex',  
//             projectSum:'a lawfirm ', 
//             btnClick:'https://jurislexlawfirm.com/', 
//           },
//           {
//             image:'/images/calc.jpeg',
//             projectTitle:'CalcIT',  
//             projectSum:'a simple calculator', 
//             btnClick:'https://mariamopeyemi.github.io/simple-calculator/', 
//           },
//           {
//             image:'/images/flip.jpeg',
//             projectTitle:'MemoFlip',  
//             projectSum:'a flip memory retention game', 
//             btnClick:'https://card-flip-memory-game.netlify.app/', 
//           },          
//           {
//             image:'/images/yebora.jpeg',
//             projectTitle:'Yebora',  
//             btnClick:'https://opeyemi-portfolio.vercel.app/', 
//           },
//           {
//             image:'/images/yeborra.jpeg',
//             projectTitle:'Shout',  
//             btnClick:'https://opeyemi-portfolio.vercel.app/', 
//           },
// ]