import React from 'react'
import { Box, Button, Typography } from '@mui/material';
import Head from 'next/head';
import ProjectCard from '../../components/card/ProjectCard';
const Projects = () => {
  return (

    <Box sx={{
      backGroundColor: 'background.paper',
      display:'flex',
      flexDirection:'column',
      alignItems: 'center',
      gap:'4rem',
      minHeight:'100vh'
    }}>
      <Head>
        <title>Projects Opeyemi - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography>
       MY PROJECTSrgb(248,208,148)brown rgb(45,42,36)coffee
      </Typography>
      <div>
       MY PROJECTS Includes
       <Box>
          <Button > All</Button>
          <Button > Vue</Button>
          <Button > JavaScript</Button>
          <Button > TypeScript</Button>
          <Button > React</Button>
          <Button > Next</Button>
          <Button > Wordpress</Button>
       </Box>
            <Typography> Vue: Yebox website</Typography>
            <Typography> Typescript: HealthXP website</Typography>
            <Typography> React: Yebora Website</Typography>
            <Typography> React: Yebora web App</Typography>
            <Typography> React: Shout web App</Typography>
            <Typography> Next: Planvest Web app</Typography>
            <Typography> Next: Portfolio Website</Typography>
            <Typography> Wordpress: Jurislex website</Typography>
        <Box sx={{display: 'flex', gap: 2, flexWrap: 'wrap', justifyContent:'space-between'}}>
          <ProjectCard projectTitle='Y' />
          <ProjectCard projectTitle='E' />
          <ProjectCard projectTitle='B' />
          <ProjectCard projectTitle='O' />
          <ProjectCard projectTitle='X' />
          <ProjectCard projectTitle='X' />
        </Box>
      </div>
    </Box>
  )
}

export default Projects