import React from 'react';
import Head from 'next/head';
import { Box, Button, Container, Grid, Typography } from '@mui/material';


const About = () => {
  return (
    <Box sx={{
      backGroundColor: 'background.paper',
      display:'flex',
      flexDirection:'column',
      alignItems: 'center',
      gap:'4rem',
      minHeight:'100vh'
    }}>
      <Head>
        <title>About Opeyemi - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {/* <Container sx={{display: 'flex', flexDirection: {xs: 'column', sm: 'row'}}}> */}
  
     <Box sx={{ display:'flex', flexDirection: 'column', alignItems:'center'}}>
     <Typography>
        ABOUT ME
      </Typography>
      <Typography>
      - Hello again-
      </Typography>

      <Typography>
          I am Afolabi Opeyemi Mariam. A product manager and software developer passionate about 
          software products and focused on building innovative solution-centric applications.
          I am focused on frontend technology and currently building products using reactJs and 
          Vanilla JavaScript. I convert Figma files to react App and ensure they have cross-browser 
          compatibility, accessibility, and responsiveness.
      </Typography>
     
     
     </Box>
    {/* </Container> */}
    </Box>
  )
}

export default About