import React, {useEffect} from "react";
import { Box, Button, Container, Grid, Typography } from "@mui/material";
import Head from "next/head";
import Aos from 'aos';
import 'aos/dist/aos.css';
import Link from "@mui/material/Link";
import Image from "next/image";


const Intro = () => {

	useEffect(() => {
		Aos.init({
			duration: 2000
		  });
	}, [])
	
	return (
		<Box
			sx={{
				backGroundColor: "background.paper",
				display: "flex",
				alignItems: "center",
				minHeight: "100vh",
				// justifyContent:'center',
				// alignContent: 'center',
				// paddingTop:'4rem',				
			}}
		>
			<Head>
				<title>Intro Opeyemi - portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container
				sx={{
					display: "flex",
					flexDirection: { xs: "column", sm: "row" },
					justifyContent:'center',
					alignContent: 'center',
					// backgroundColor:'red',
				}}
			>
				<Box
				data-aos='fade-right'
					sx={{
						flex: "1",
						border: {xs:"2px black solid", sm:'none'},
						borderRadius: {xs:"50%"},
						padding: {xs:"2rem"},
						width: {xs:"250px"},
						height: {xs:"250px"},
						marginBottom: {xs:"2rem"},
						// backGroundColor:'secondary'
					}}
				>
					<Image
						src="/images/me.jpeg"
						alt="my image"
						width="200px"
						height="200px"
						style={{ borderRadius: "50%" }}
					/>
				</Box>
				<Box
					data-aos='fade-left'
					sx={{
						flex: "1",
						display: "flex",
						flexDirection: "column",
						alignItems: "center",
						margin:"auto",
					}}
				>
					<Typography>Hello World 👋, I am Afolabi Opeyemi,</Typography>
					<Typography>a Front-end Developer from Lagos, Nigeria.</Typography>
					<Typography
						sx={{
							display: "flex",
							alignItems: "center",
							textAlign: { xs: "none", md: "center" },
						}}
					>
						goal and growth minded who constantly seeks out innovative scalable
						solutions to everyday problems.
					</Typography>
					<Box sx={{ marginY: "1rem", display: "flex", gap: "2rem" }}>
						<Link
							target="_blank"
							rel="noreferrer noopener"
							href="/doc/DEV_AFOLABI_OPEYEMI_CV.pdf"
							sx={{
								textDecoration: "none",
								color: "white",
							}}
						>
							<Button variant="contained" color="secondary"
								data-aos='zoom-in-left'
							sx={{ 
								"&:hover": {
								  color: 'gray',
								  backgroundColor: 'black',
								},
							  }}>
								Resume
							</Button>
						</Link>
						<Link
							target="_blank"
							rel="noreferrer noopener"
							href="https://medium.com/@opeyemi.afolabi45"
							sx={{
								textDecoration: "none",
								color: "white",
							}}
						>
							<Button
								data-aos='zoom-in-right'
								// data-aos-duration='5000'
								variant="contained"
								color="secondary"
								sx={{ 
									"&:hover": {
									color: 'gray',
									backgroundColor: 'black',
									},
								}}
							>
								Blog
							</Button>
						</Link>
						{/* <Button
							variant="contained"
							color="secondary"
							href="mailto:opeyemi.dev@gmail.com"
							sx={{ 
								"&:hover": {
								  color: 'gray',
								  backgroundColor: 'black',
								},
							  }}
						>
							Contact
						</Button> */}
					</Box>
				</Box>
			</Container>
		</Box>
	);
};

export default Intro;
